#!/usr/bin/env bash

set -eu

script_name="${BASH_SOURCE:-$0}"
script_path=$(realpath "$script_name")
script_dir_path=$(dirname "$script_path")
workspace_dir=$(dirname "$script_dir_path")
dynamic_plugins_root_dir="$workspace_dir/dynamic-plugins-root"

REGISTRY_URL="${REGISTRY_URL:-quay.io}"
ORG_ID="${ORG_ID:-redhat-resource-optimization}"
REPO="${REPO:-dynamic-plugins}"
VERSION="${VERSION:-}"

function _usage {
  cat <<EOF
Usage: 
  $script_name clean
  VERSION=<semver> $script_name [publish|pack]

Environment variables:
  VERSION         Required. The new plugin version. This values is reflected in every package.json and other manifest files.
  REGISTRY_URL    Default: "quay.io"
  ORG_ID          Default: "redhat-resource-optimization"
  REPO            Default: "dynamic-plugins"

Sub-commands:
  clean      Removes directories generated by this script.
  export     Generates the dynamic plugins and exports them to $dynamic_plugins_root_dir.
  publish    Builds and pushes the container image to a repository specified by the environment variables
EOF
}

function _pocker {
  $(command -v podman || command -v docker) "$@"
}

function _januscli_dynamic_plugins {
  local args=( )
  if command -v docker; then
    args+=( --container-tool docker )
  fi
  yarn janus-cli package package-dynamic-plugins "${args[@]}" "$@"
}

function clean {
  rm -rf "$dynamic_plugins_root_dir"
  rm -rf "$workspace_dir/dist-types"
  rm -rf "$workspace_dir"/plugins/*/dist-dynamic
  rm -rf "$workspace_dir"/plugins/*/dist
  rm -rf "$workspace_dir"/packages/*/dist
}

function _update_version {
  for dir in $(ls -1d plugins/* | tail -n +2); do
    cd "$(realpath $dir)"
    yarn version $VERSION --immediate
    cd -
  done
}

function export {
  _update_version
  yarn tsc
  yarn build:all
  _januscli_dynamic_plugins --export-to "$dynamic_plugins_root_dir"
  git restore plugins/*/package.json
}

function publish {
  if [[ -z "$VERSION" ]]; then
    echo "Error: The VERSION environment variable must be provided" 
    exit 1
  fi

  if [[ ! ($VERSION =~ ^[0-9]\.[0-9]\.[0-9]) ]]; then
    echo "Error: The VERSION environment variable value doesn't match: /^[0-9]\.[0-9]\.[0-9]/" 
    exit 2
  fi

  _update_version
  yarn tsc
  yarn build:all
  _januscli_dynamic_plugins --tag "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION"
  git restore plugins/*/package.json

  commit_sha=$(git rev-parse --short=6 HEAD)
  _pocker image tag "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION" "$REGISTRY_URL/$ORG_ID/$REPO:$commit_sha"
  _pocker image tag "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION" "$REGISTRY_URL/$ORG_ID/$REPO:latest"
  _pocker push "$REGISTRY_URL/$ORG_ID/$REPO:$commit_sha"
  _pocker push "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION"
  _pocker push "$REGISTRY_URL/$ORG_ID/$REPO:latest"
}

if [[ $# -eq 0 || $1 =~ -h|--help ]]; then
  _usage
else
  command="$1"
  if [[ ! "$command" =~ ^_ ]]; then
    "$command"
  else
    _usage
  fi
fi
